name: estimation_list_generator
description: "A new Flutter project that lets user to generate a document with a letter head format and aims to reduce khmer input time consumption."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  gap: ^3.0.1
  pdf: ^3.11.1
  flutter_svg: ^2.0.17
  package_info_plus: ^8.1.3
  window_manager: ^0.4.3
  url_launcher: ^6.3.1
  pinput: ^5.0.1
  lottie: ^3.3.0
  flutter_animate: ^4.5.2
  easy_rich_text: ^2.2.0
  font_awesome_flutter: ^10.8.0
  supabase_flutter: ^2.8.3
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_confetti: ^0.3.4
  choice: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: MoulLight
      fonts:
        - asset: assets/fonts/KhmerOS-Muol_Light.ttf
    - family: Dangrek
      fonts:
        - asset: assets/fonts/Dangrek-Regular.ttf
    - family: Siemreap
      fonts:
        - asset: assets/fonts/Siemreap-Regular.ttf
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/Kantumruy-Regular.ttf
